# Generated by Django 5.2.4 on 2025-08-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='please do not change this field Thank you.', max_length=150, unique=True),
        ),
    ]
