# Generated by Django 5.2.4 on 2025-08-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
